#!/usr/bin/env bash
# =============================================================================
# New Client Onboarding Script
# Owner: Jayavarsan (Kubernetes Lead)
#
# Creates all Kubernetes resources for a new tenant in < 10 minutes.
#
# Usage:
#   chmod +x scripts/onboard_client.sh
#   ./scripts/onboard_client.sh <client-id> <client-domain> [replicas]
#
# Example:
#   ./scripts/onboard_client.sh tesla tesla.bi-platform.io 2
# =============================================================================

set -euo pipefail   # Exit on error, unset var, or pipe failure

# ── Validate arguments ─────────────────────────────────────────
if [ $# -lt 2 ]; then
  echo "Usage: $0 <client-id> <client-domain> [replicas]"
  echo "Example: $0 tesla tesla.bi-platform.io 2"
  exit 1
fi

CLIENT_ID="$1"         # e.g., tesla
CLIENT_DOMAIN="$2"     # e.g., tesla.bi-platform.io
REPLICAS="${3:-2}"     # Default 2 replicas
NAMESPACE="client-${CLIENT_ID}"
OVERLAY_DIR="k8s/overlays/${NAMESPACE}"
ECR_IMAGE="123456789.dkr.ecr.us-east-1.amazonaws.com/bi-platform:latest"

echo "======================================="
echo " Onboarding New Client: ${CLIENT_ID}"
echo "======================================="
echo "Namespace:  ${NAMESPACE}"
echo "Domain:     ${CLIENT_DOMAIN}"
echo "Replicas:   ${REPLICAS}"
echo "Image:      ${ECR_IMAGE}"
echo ""

# ── Step 1: Create overlay directory ──────────────────────────
echo "[1/6] Creating Kustomize overlay..."
mkdir -p "${OVERLAY_DIR}"

# ── Step 2: Generate kustomization.yaml ───────────────────────
cat > "${OVERLAY_DIR}/kustomization.yaml" <<EOF
# Auto-generated by onboard_client.sh for client: ${CLIENT_ID}
# Generated on: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: ${NAMESPACE}

configMapGenerator:
  - name: client-config
    literals:
      - CLIENT_ID=${CLIENT_ID}
      - ENVIRONMENT=production

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bi-platform-app
        labels:
          app.bi-platform/tenant: "true"
          app.bi-platform/client: "${CLIENT_ID}"
      spec:
        replicas: ${REPLICAS}

  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: bi-platform-ingress
      spec:
        rules:
          - host: ${CLIENT_DOMAIN}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: bi-platform-svc
                      port:
                        number: 80

images:
  - name: REGISTRY/bi-platform
    newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/bi-platform
    newTag:  latest
EOF

echo "    ✅ Overlay created: ${OVERLAY_DIR}/kustomization.yaml"

# ── Step 3: Create namespace with labels ──────────────────────
echo "[2/6] Creating namespace: ${NAMESPACE}..."
kubectl create namespace "${NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

# Label the namespace so CD pipeline discovers it automatically
kubectl label namespace "${NAMESPACE}" \
  "app.bi-platform/tenant=true" \
  "app.bi-platform/client=${CLIENT_ID}" \
  --overwrite

echo "    ✅ Namespace ready"

# ── Step 4: Apply ECR pull secret to new namespace ─────────────
echo "[3/6] Setting up image pull secret..."
# Copy ECR secret from default namespace (created during cluster setup)
kubectl get secret ecr-registry-secret \
  --namespace=default \
  --export -o yaml 2>/dev/null | \
  sed "s/namespace: default/namespace: ${NAMESPACE}/" | \
  kubectl apply -f - || \
  echo "    ⚠️  ecr-registry-secret not found in default — skipping (add manually)"

echo "    ✅ Pull secret configured"

# ── Step 5: Apply Kubernetes manifests ────────────────────────
echo "[4/6] Applying Kubernetes manifests..."
kubectl apply -k "${OVERLAY_DIR}"
echo "    ✅ Manifests applied"

# ── Step 6: Wait for pods to be ready ─────────────────────────
echo "[5/6] Waiting for deployment to be ready..."
kubectl rollout status deployment/bi-platform-app \
  --namespace="${NAMESPACE}" \
  --timeout=120s
echo "    ✅ Deployment is ready"

# ── Step 7: Smoke test ─────────────────────────────────────────
echo "[6/6] Running smoke test..."
POD=$(kubectl get pods -n "${NAMESPACE}" -l app=bi-platform-app -o jsonpath='{.items[0].metadata.name}')
HEALTH=$(kubectl exec -n "${NAMESPACE}" "${POD}" -- \
  python -c "import urllib.request, json; r=urllib.request.urlopen('http://localhost:5000/health'); print(json.loads(r.read())['status'])")

if [ "${HEALTH}" = "healthy" ]; then
  echo "    ✅ Health check passed: ${HEALTH}"
else
  echo "    ❌ Health check FAILED: ${HEALTH}"
  exit 1
fi

# ── Summary ────────────────────────────────────────────────────
echo ""
echo "======================================="
echo " ✅ Client '${CLIENT_ID}' is LIVE!"
echo "======================================="
echo "Namespace:  ${NAMESPACE}"
echo "URL:        https://${CLIENT_DOMAIN}"
echo "Pods:       ${REPLICAS} replicas"
echo ""
echo "Useful commands:"
echo "  kubectl get pods -n ${NAMESPACE}"
echo "  kubectl logs -n ${NAMESPACE} -l app=bi-platform-app"
echo "  kubectl describe deployment bi-platform-app -n ${NAMESPACE}"
